// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQYfenAr5ZrSvKPE7A_LUUu9AlxMgNBR4',
    appId: '1:733498307256:web:8a023fe572b6c2510ffa4d',
    messagingSenderId: '733498307256',
    projectId: 'instagram-aad02',
    authDomain: 'instagram-aad02.firebaseapp.com',
    storageBucket: 'instagram-aad02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR2_0HBDhZ0U0eiD0R48Ztc_BsqM9vZxA',
    appId: '1:733498307256:android:912506dcd2272c750ffa4d',
    messagingSenderId: '733498307256',
    projectId: 'instagram-aad02',
    storageBucket: 'instagram-aad02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2i_iAukxKSTzGeDxUjMbWHLFYwL-lxNA',
    appId: '1:733498307256:ios:d8bc1b1888cffbfe0ffa4d',
    messagingSenderId: '733498307256',
    projectId: 'instagram-aad02',
    storageBucket: 'instagram-aad02.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2i_iAukxKSTzGeDxUjMbWHLFYwL-lxNA',
    appId: '1:733498307256:ios:9f189d6522534f3f0ffa4d',
    messagingSenderId: '733498307256',
    projectId: 'instagram-aad02',
    storageBucket: 'instagram-aad02.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
